# Generated by Django 5.2.5 on 2025-08-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_auto_20250829_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
